entryPoints:
  web:
    address: ":7860"

providers:
  file:
    filename: /home/nocodb/app/traefik/dynamic_conf.yml
    watch: true

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

accessLog: {}